### ISSUE TITLE
Copy typo

### ISSUE THREAD

**Issue by paul-pro** [adjust-design-system/design-tokens#23]
Hi! Don't know if it is the actual version, but there is a typo in the word `Collection`:
https://github.com/adjust-design-system/design-tokens/blob/23a946401e5bf87b98be69699691dca8670fc588/src/templates/index.njk#L27

**Comment by reimar** [comment]
Thank you, I just fixed it :)

> Don't know if it is the actual version …

We are currently planning to move all content over to our main documentation website, naming for a somewhat official first release. We will also update the design (currently using the standard [docusaurus](https://docusaurus.io) theme).
