### ISSUE TITLE
Go over core components font weight 

### ISSUE THREAD

**Issue by benni345** [adjust-design-system/design-tokens#68]
**Problem:**
Since we are looking at our colour pallet and want to assure all our text is legible. We discussed looking at font weight for core components such as buttons and selects and maybe changing them one scale up (primary button from medium to semi bold) 
**Tasks:**

- [ ] Check if it makes sense to scale up font weight for core components 
- [ ] Update all symbols with new font weights 

**Acceptance Criteria**:
Symbols and Index has been updated

**Comment by reimar** [comment]
One important thing! When we do that, the very text layers will slightly grow in with. That’s not a problem but we need to double-check all affected symbols in order to maintain the correct right padding.
